### ISSUE TITLE
fatal error: 'bifrost/ColoredCDBG.hpp' file not found

### ISSUE THREAD

**Issue by Modupeh** [nluhmann/BlastFrost#2] opened 2020-02-11 17:23 UTC
Hi I am trying out BlastFrost and have the error / fatal error: 'bifrost/ColoredCDBG.hpp' file not found/ #include <bifrost/ColoredCDBG.hpp> and the programmed did not install. I have attached a screenshot here. All previous steps up to the final 'make' command seem to have worked fine. I install Bifrost in a similar way without any problems. ho who I resolve this? I'm working on a Mac. 
![Screen Shot 2020-02-11 at 5 15 46 PM](https://user-images.githubusercontent.com/25081414/74261540-511f6f80-4cf3-11ea-8be1-9dc4ce1f0fa7.png)

**Comment by nluhmann** [comment] 2020-02-12 11:33
Hello,
it seems that Bifrost is not installed correctly on your system, hence BlastFrost has a problem to find Bifrost. Can you run Bifrost directly without problems (e.g. see the command line interface instructions)? Did you forget to make install Bifrost? Can you check the troubleshooting section in the Bifrost repo if that might cause a problem?

**Comment by Modupeh** [comment] 2020-02-12 13:04
Hi Nina. I am able to run bifrost without problems (see command line screen shot) and have generated a a bfg_colors and gfa files using bifrost. I have just reinstalled it again following all the steps but still ran into the same issue with Blastfrost. The files Blastfrost seem to be trying to invoke can be seem in bifrost/src/. Is there a location on Blastfrost that I can move these files to be on the path for BlastFrst
<img width="1158" alt="Screen Shot 2020-02-12 at 12 53 27 PM" src="https://user-images.githubusercontent.com/25081414/74337468-3fdc6e80-4d98-11ea-8c86-ebecf4a9a9f5.png">

**Comment by GuillaumeHolley** [comment] 2020-02-12 13:44
Hi Modupeh,

It seems to me the issue is Blastfrost not finding Bifrost since we know now you have successfully compiled and run Bifrost. At this point, I think its a problem with environment variables.

When you installed Bifrost, did you do a `make install` ? If you did, the Bifrost header files (the one ending on .hpp or .tcc) should be located by default in `/usr/local/include/bifrost/`. Also, could you make sure that your environment variables `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` point to `/usr/local/include/` ?

Best,
Guillaume

**Comment by jkoszucki** [comment] 2020-02-13 12:23
Hi all,

in fact I had exactly same issue as @Modupeh. After setting environment variables `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH` both to `/usr/local/include/` I've got following warnings. 

![Zrzut ekranu 2020-02-13 o 13 17 19](https://user-images.githubusercontent.com/59886644/74434846-8ea30a80-4e63-11ea-8ab8-8595b1a427a8.png)

**Comment by GuillaumeHolley** [comment] 2020-02-15 10:47
Hello Januz,

It seems to me this is again a new environment variables problem. By setting `C_INCLUDE_PATH` and `CPLUS_INCLUDE_PATH`, your OS now knows where are the headers of Bifrost. For some reason, it doesn't know where is the Bifrost library file. For that, you must set `LD_LIBRARY_PATH`, `LIBRARY_PATH` and `PATH` with `/usr/local/lib/` [(Bifrost Troubleshooting)](https://github.com/pmelsted/bifrost#troubleshooting).

The problem here is... Apple. Well, Mac OS technically. All this environment variable thingy is pretty standard on Linux and you (almost) never have to worry about it. Apparently, it is a problem on Mac for a long time now and the solution is to... install Xcode (see [stupid solution](https://stackoverflow.com/questions/23905661/on-mac-g-clang-fails-to-search-usr-local-include-and-usr-local-lib-by-def)). Or you can use the solution with the `export` I am providing in in the [(Bifrost Troubleshooting)](https://github.com/pmelsted/bifrost#troubleshooting). This solution is only temporary, for the duration of your current session. You can make this permanent by modifying your `.bashrc` (see [permament export](https://stackoverflow.com/questions/13046624/how-to-permanently-export-a-variable-in-linux)).

In general, we will make a bioconda package to ease the install for Mac users. Let me know how it goes and if we can help you further.

Best,
Guillaume

**Comment by Modupeh** [comment] 2020-02-16 00:38
Hi Guillaume,

Thanks for the response. I did the C_INCLUDE_PATH following instructions on Bifrost last week and was able to get it to work. But have now decide to wait until the bioconda package is published.  Here is the latest issue I encountered. Blastfrost worked nicely on the test data provided with the download and I was able to get subgraphs which I was able to export and make plots. On my actual data (2 pneumococcal assembled genomes to test), I got a bifrost output of of the 2 expected files but the subgraph command would not work on this using Blastfrost. My feeling is that the bifrost outputs may have been corrupted (speculating) given how quick the analysis completed (~0.9 secs I think). I would have attached the bifrost outputs and the query sequence for your troubleshooting needs but file types are not supported.

Very much looking forward to the condo package.

**Comment by nluhmann** [comment] 2020-02-17 09:57
Hi Modupeh,
great to hear your installation seems to have worked now. I am happy to look into your subgraph issue if you want, just you send me your graph and query (N.Luhmann@warwick.ac.uk).

I will close this issue as the installation problems have been resolved.

**Closed by nluhmann** 2020-02-17 09:57 UTC
